<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/"><channel><title>mypy on Jürgen Gmach</title><link>https://jugmac00.github.io/tags/mypy/</link><description>Recent content in mypy on Jürgen Gmach</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Fri, 12 Nov 2021 16:12:43 +0100</lastBuildDate><atom:link href="https://jugmac00.github.io/tags/mypy/index.xml" rel="self" type="application/rss+xml"/><item><title>Why Do We Get Different Results From Mypy</title><link>https://jugmac00.github.io/til/why-do-we-get-different-results-from-mypy/</link><pubDate>Fri, 12 Nov 2021 16:12:43 +0100</pubDate><guid>https://jugmac00.github.io/til/why-do-we-get-different-results-from-mypy/</guid><description>My colleague added mypy as a test environment for our tox setup.
When I checked out his branch and ran it on my machine, it failed.
The error does not matter, but fwiw it was about that one upstream package has forgotten to include a py.typed file, a topic which I dedicated a whole blog post.
The interesting part was&amp;hellip; why did it work on his machine, but not on mine?</description></item></channel></rss>